name: S3, Cloudfront and R53 deployment for www_frontend
#Triggers the workflow on push request events to main branch
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Deploy S3, Cloudfront and R53
      uses: youyo/aws-sam-action/python3.8@master
      run: |
        aws cloudformation deploy --template-file template.yaml --s3-bucket aws-cli-wwwresume-fe-template --s3-prefix wwwResumeAppFE --stack-name wwwResumeAppFE --capabilities CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset
    - name: Sync S3 bucket
      run: |
        aws s3 sync www/ s3://resume.lhtran.com --acl private
    - name: Invalidate Cloudfront cache
      run: |
        aws configure set preview.cloudfront true
        aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"
    - name: Install test dependencies
      run: |
        pip install -r tests/requirements.txt
    - name: Run integration test
      run: |
        pytest tests/integration